# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root-password-2
      MYSQL_DATABASE: my-database-102
      MYSQL_USER: my-user-102
      MYSQL_PASSWORD: my-password-102
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data: